pg_jobmon first commit from mac
cfpb/pg_jobmon pull request #1
Opened 2016-01-14 15:27 UTC by olivermel

2016-01-14 15:58 UTC, Scotchester commented
Hello! Please follow the instructions at the top of the [cfpb/open-source-project-template](https://github.com/cfpb/open-source-project-template) README and update this PR accordingly. Thank you.

2016-01-14 16:04 UTC, tanderegg commented
@Scotchester thanks, we should be following that more strictly.  This is actually just a repo to build an RPM, so we'll probably cut back on the documentation a bit since that may be overkill.  @olivermel, please take as much from the cfpb/open-source-project-template repo as you think is applicable, thanks!

2016-01-14 16:11 UTC, Scotchester commented
Sure thing, @tanderegg. Not all of it will be applicable. The important things are TERMS, CONTRIBUTING, LICENSE, and CHANGELOG. The install and use docs can be light-touch, if that is more appropriate for a project like this.

2016-01-14 16:13 UTC, Scotchester commented
P.S.: @olivermel, take a look at how the README is rendering https://github.com/olivermel/pg_jobmon/

You'll want to format those code blocks so they are a bit easier to follow.

2016-01-14 16:41 UTC, tanderegg commented on README.md
> +nstall
@olivermel typo here, should say "install"

2016-01-14 19:31 UTC, tanderegg commented on bootstrap-pgmon.sh
> +
@olivermel Please make sure only the packages actually required to build are listed here (not vim, tree, etc.)

2016-02-04 21:11 UTC, tanderegg commented on bootstrap-pgmon.sh
> + ln -sf /Users/ezeogum/Projects/pg_mon.task/SPECS $HOME/rpmbuild/SPECS
Your username directory is hardcoded here!

2016-02-04 21:11 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +%define pg_dir /usr/pgsql-9.4
Just like in IMCS, we need to remove the %define here, and mention the fact that --define must be passed on the command line when running rpmbuild.

2016-02-04 21:11 UTC, tanderegg commented on README.md
> +    4. Run "rpmbuild -ba SPECS/pg_jobmon.spec" to build the pg_jobmon rpm package.
Refer to the --define option here

2016-02-04 21:12 UTC, tanderegg commented on README.md
> +    3. Run "rpmbuild -ba /SPECS/pg_jobmon.spec"
... and here

2016-02-04 21:58 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +source %{buildroot}/etc/profile.d/pg_jobmon.sh
Is it necessary to create this file and then source it?  I don't think it is needed when pg_jobmon is being used, only when the RPM is being built.  So we could reduce this to just running the "export" lines directly before %make_install, and avoid adding unnecessary files to the package.

2016-02-04 22:07 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +/usr/share/doc/pgsql/extension/pg_jobmon.md
This should be %{pg_dir}/doc/extension/pg_jobmon.md

2016-09-23 14:25 UTC, tanderegg commented on bootstrap.sh
> +SCRIPTPATH=$(dirname "$SCRIPT")
Missing:
```
SCRIPT=$(readlink -f "$0")
```

2016-09-23 14:26 UTC, tanderegg commented on bootstrap.sh
> +  mkdir -p $HOME/rpmbuild/{BUILD,RPMS,SOURCES,SRPMS}
Please fix the indentation on these lines

2016-09-23 14:28 UTC, tanderegg commented on .gitignore
> +bootstrap.sh-mine
Please remove this file, as it is not normally present.

2016-09-23 14:28 UTC, tanderegg commented on INSTALL.md
> +4. Run rpmbuild -ba SPECS/pg_jobmon.spec --define 'pg_dir /usr/pgsql-9.4' to build the pg_jobmon rpm package.
Add in the _suffix define.

2016-09-23 14:28 UTC, tanderegg commented on INSTALL.md
> +3. Run rpmbuild -ba /SPECS/pg_jobmon.spec 'pg_dir /usr/pgsql-9.4'
Here too

2016-09-23 14:28 UTC, tanderegg commented on README.md
> +    4. Run rpmbuild -ba SPECS/pg_jobmon.spec --define 'pg_dir /usr/pgsql-9.5'--define 'suffix 95' to build the pg_jobmon rpm package.
_suffix

2016-09-23 14:28 UTC, tanderegg commented on README.md
> +    3. Run rpmbuild -ba /SPECS/pg_jobmon.spec --define 'pg_dir /usr/pgsql-9.5' --define 'suffix 95'
_suffix

2016-09-23 14:28 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +Name:           pg_jobmon%{suffix}
_suffix

2016-09-23 14:28 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +Obsoletes:      pg_jobmon%{suffix} <= 1.3.0
_suffix

2016-09-23 14:28 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +Provides:       pg_jobmon%{suffix} => 1.3.1
_suffix

2016-09-23 14:28 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +BuildRequires: postgresql-devel, postgresql
Should actually be: `postgresql%{_suffix}-devel, postgresql${_suffix}`

2016-09-23 14:28 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +source %{buildroot}/etc/profile.d/pg_jobmon.sh
Again, we don't want these lines in here, these are only required for building the RPM, not for using it.

2016-09-23 14:28 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +Provides:       pg_jobmon%{suffix} => 1.3.1
Also, should be `=` not `=>`

2016-09-23 14:33 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +/usr/pgsql-9.5
Remove these two lines and replace with the actual files in the extension, such as:
```
%{pg_dir}/doc/extension/pg_jobmon.md
%{pg_dir}/share/extension/pg_jobmon--0.2.0--0.2.1.sql
...
...
%{pg_dir}/share/extension/pg_jobmon.control
```

2016-09-23 14:37 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +%make_install
This should be:
`make install USE_PGXS=1 DESTDIR=${RPM_BUILD_ROOT}`

2016-09-23 14:37 UTC, tanderegg requested changes

2016-09-26 17:36 UTC, tanderegg commented on SPECS/pg_jobmon.spec
> +%{pg_dir}
@olivermel Please list the actual files here rather than the whole directory.  This ensures that unexpected files do not get added to the RPM.

2017-12-14 19:57 UTC, Scotchester commented
Hey @tanderegg, is this repo still going to be used for anythign? If not, I think I'll archive or delete it.

2017-12-14 20:29 UTC, tanderegg commented
@Scotchester We did actually build against the fork, I should merge this Pull Request and keep it around in case we need to rebuild the RPM, if that's cool.

2017-12-14 20:30 UTC, merged

2017-12-14 20:31 UTC, Scotchester commented
:+1: I was just going through old GitHub mentions and noticed it hanging out there :)